from pathlib import Path
from bs4 import BeautifulSoup
import json,re
ROOT=Path(__file__).resolve().parents[1]; BASE='https://jami-protect.github.io/jami-protect'
locs=['en','nl','de','fr']
NAV={'en':('Open menu','Close menu','Language'),'nl':('Menu openen','Menu sluiten','Taal'),'de':('Menü öffnen','Menü schließen','Sprache'),'fr':('Ouvrir le menu','Fermer le menu','Langue')}
REPL={
'nl':{'SYSTEM ANALYSIS READY':'SYSTEEMANALYSE GEREED','Game detected':'Game gedetecteerd','Hardware match':'Hardwarematch','Recommended actions':'Aanbevolen acties','Restore plan':'Herstelplan','✓ Ready':'✓ Gereed','✓ Complete':'✓ Voltooid','✓ Explained':'✓ Uitgelegd','✓ Prepared':'✓ Voorbereid','CONSISTENCY FIRST':'CONSISTENTIE EERST','MATCHED':'GEMATCHT','EVIDENCE':'BEWIJS','VISIBLE':'ZICHTBAAR','DETECT → EXPLAIN → RECOMMEND → RESTORE':'DETECTEER → LEG UIT → ADVISEER → HERSTEL','Browser memory':'Browsergeheugen','Tabs / media / background':'Tabs / media / achtergrond','Clients / update services':'Clients / updateservices','Capture / social / monitoring':'Opname / sociaal / monitoring','Startup pressure':'Opstartdruk','Background apps':'Achtergrondapps','Simpel Mode':'Eenvoudige modus','Gamer Mode':'Gamer-modus'},
'de':{'SYSTEM ANALYSIS READY':'SYSTEMANALYSE BEREIT','Game detected':'Spiel erkannt','Hardware match':'Hardware-Abgleich','Recommended actions':'Empfohlene Aktionen','Restore plan':'Wiederherstellungsplan','✓ Ready':'✓ Bereit','✓ Complete':'✓ Vollständig','✓ Explained':'✓ Erklärt','✓ Prepared':'✓ Vorbereitet','CONSISTENCY FIRST':'KONSISTENZ ZUERST','MATCHED':'ABGEGLICHEN','EVIDENCE':'NACHWEISE','VISIBLE':'SICHTBAR','DETECT → EXPLAIN → RECOMMEND → RESTORE':'ERKENNEN → ERKLÄREN → EMPFEHLEN → WIEDERHERSTELLEN','Browser memory':'Browser-Speicher','Tabs / media / background':'Tabs / Medien / Hintergrund','Clients / update services':'Clients / Update-Dienste','Capture / social / monitoring':'Capture / Social / Monitoring','Startup pressure':'Autostart-Last','Background apps':'Hintergrund-Apps','Simple Mode':'Einfacher Modus','Gamer Mode':'Gamer-Modus'},
'fr':{'SYSTEM ANALYSIS READY':'ANALYSE SYSTÈME PRÊTE','Game detected':'Jeu détecté','Hardware match':'Matériel analysé','Recommended actions':'Actions recommandées','Restore plan':'Plan de restauration','✓ Ready':'✓ Prêt','✓ Complete':'✓ Terminé','✓ Explained':'✓ Expliqué','✓ Prepared':'✓ Préparé','CONSISTENCY FIRST':'RÉGULARITÉ D’ABORD','MATCHED':'ADAPTÉ','EVIDENCE':'PREUVES','VISIBLE':'VISIBLES','DETECT → EXPLAIN → RECOMMEND → RESTORE':'DÉTECTER → EXPLIQUER → RECOMMANDER → RESTAURER','Browser memory':'Mémoire du navigateur','Tabs / media / background':'Onglets / médias / arrière-plan','Clients / update services':'Clients / services de mise à jour','Capture / social / monitoring':'Capture / social / monitoring','Startup pressure':'Charge au démarrage','Background apps':'Applications en arrière-plan','Simple Mode':'Mode simple','Gamer Mode':'Mode gamer'}}
PRIV={
'en':('Privacy','JaMi Protect is currently a static GitHub Pages preview. We keep data collection deliberately small and do not run JaMi-owned advertising or analytics trackers on this site.',[
('What this site collects','JaMi Protect itself does not set analytics cookies or build advertising profiles on this static preview. GitHub Pages hosting may log visitor IP addresses for security purposes; GitHub handles that hosting data under its own privacy statement.'),('Contact and review emails','If you contact JaMi Protect or submit the review form, your email application sends the information you choose to include directly by email. Your email address is used for the conversation, support or feedback and is not shown in a public review.'),('Public reviews','A review is only eligible for public publication when you explicitly select the publication-consent option. You can later withdraw consent for future public display by contacting JaMi Protect.'),('Purpose and retention','Contact and feedback information is used to answer messages, evaluate feedback and, only with consent, prepare a public community review. It should be kept only as long as reasonably needed for those purposes or a related request.'),('Third-party services','This site is hosted by GitHub Pages. External links such as Steam, SteamGridDB and GitHub have their own privacy practices.'),('Your choices','You can use the website without sending a form. You can request correction or deletion of information you previously sent via the contact address on the Contact page.')]),
'nl':('Privacy','JaMi Protect is momenteel een statische GitHub Pages-preview. We houden gegevensverzameling bewust klein en gebruiken op deze site geen eigen advertentie- of analysetrackers.',[
('Wat deze site verzamelt','JaMi Protect zelf plaatst op deze statische preview geen analyticscookies en bouwt geen advertentieprofielen op. GitHub Pages kan IP-adressen van bezoekers loggen voor beveiligingsdoeleinden; GitHub verwerkt die hostinggegevens volgens zijn eigen privacyverklaring.'),('Contact- en reviewmails','Als je contact opneemt of het reviewformulier gebruikt, verstuurt jouw mailapp de informatie die je zelf invult rechtstreeks per e-mail. Je e-mailadres wordt gebruikt voor het gesprek, support of feedback en wordt niet in een openbare review getoond.'),('Openbare reviews','Een review komt alleen in aanmerking voor openbare publicatie wanneer je expliciet toestemming voor publicatie aanvinkt. Je kunt die toestemming voor toekomstige openbare weergave later intrekken.'),('Doel en bewaartermijn','Contact- en feedbackgegevens worden gebruikt om berichten te beantwoorden, feedback te beoordelen en, alleen met toestemming, een openbare communityreview voor te bereiden. Bewaar gegevens niet langer dan redelijk nodig is voor die doelen of een bijbehorend verzoek.'),('Externe diensten','Deze site wordt gehost via GitHub Pages. Externe links zoals Steam, SteamGridDB en GitHub hebben hun eigen privacybeleid.'),('Jouw keuzes','Je kunt de website gebruiken zonder een formulier te versturen. Je kunt via het contactadres op de Contact-pagina correctie of verwijdering vragen van eerder verstuurde informatie.')]),
'de':('Datenschutz','JaMi Protect ist derzeit eine statische GitHub-Pages-Vorschau. Die Datenerhebung wird bewusst klein gehalten; eigene Werbe- oder Analytics-Tracker werden nicht eingesetzt.',[
('Welche Daten diese Seite erfasst','JaMi Protect selbst setzt keine Analytics-Cookies und erstellt keine Werbeprofile. GitHub Pages kann IP-Adressen von Besuchern zu Sicherheitszwecken protokollieren; GitHub verarbeitet diese Hosting-Daten nach der eigenen Datenschutzerklärung.'),('Kontakt- und Review-E-Mails','Wenn du JaMi Protect kontaktierst oder das Review-Formular nutzt, sendet dein E-Mail-Programm die gewählten Angaben direkt per E-Mail. Deine E-Mail-Adresse wird für die Unterhaltung, Support oder Feedback verwendet und nicht in einer öffentlichen Review angezeigt.'),('Öffentliche Reviews','Eine Review kann nur öffentlich veröffentlicht werden, wenn du die Veröffentlichungs-Einwilligung ausdrücklich auswählst. Diese Einwilligung kann für eine zukünftige Anzeige später widerrufen werden.'),('Zweck und Aufbewahrung','Kontakt- und Feedbackdaten werden genutzt, um Nachrichten zu beantworten, Feedback auszuwerten und, nur mit Einwilligung, eine öffentliche Community-Review vorzubereiten. Daten sollen nur so lange aufbewahrt werden, wie sie dafür vernünftigerweise benötigt werden.'),('Drittanbieter','Diese Website wird über GitHub Pages gehostet. Externe Links wie Steam, SteamGridDB und GitHub haben eigene Datenschutzpraktiken.'),('Deine Wahlmöglichkeiten','Du kannst die Website nutzen, ohne ein Formular abzusenden. Über die Kontaktseite kannst du die Berichtigung oder Löschung zuvor gesendeter Informationen anfordern.')]),
'fr':('Confidentialité','JaMi Protect est actuellement une preview statique hébergée sur GitHub Pages. Nous limitons volontairement la collecte de données et n’utilisons pas de trackers publicitaires ou analytiques propres à JaMi.',[
('Ce que ce site collecte','JaMi Protect ne dépose pas de cookies analytics et ne crée pas de profils publicitaires. GitHub Pages peut journaliser les adresses IP des visiteurs à des fins de sécurité; GitHub traite ces données d’hébergement selon sa propre déclaration de confidentialité.'),('E-mails de contact et avis','Si vous contactez JaMi Protect ou utilisez le formulaire d’avis, votre application e-mail envoie directement les informations choisies. Votre adresse e-mail sert à la conversation, au support ou au feedback et n’est pas affichée dans un avis public.'),('Avis publics','Un avis n’est éligible à une publication publique que si vous cochez explicitement le consentement à la publication. Vous pouvez ensuite retirer ce consentement pour un affichage public futur.'),('Finalité et conservation','Les informations de contact et de feedback servent à répondre aux messages, évaluer les retours et, uniquement avec consentement, préparer un avis communautaire public. Elles ne devraient être conservées que pendant la durée raisonnablement nécessaire.'),('Services tiers','Ce site est hébergé par GitHub Pages. Les liens externes comme Steam, SteamGridDB et GitHub ont leurs propres pratiques de confidentialité.'),('Vos choix','Vous pouvez utiliser le site sans envoyer de formulaire. Vous pouvez demander la correction ou la suppression d’informations déjà envoyées via l’adresse indiquée sur la page Contact.')])}
REV={'en':('I consent to JaMi Protect publishing this review publicly (my email address will not be published).','Mail app did not open? Copy the review below and send it manually.','Copy review text','Please choose a rating.','Your mail app should open. If it does not, use the copy fallback below.','Review copied to your clipboard.'),'nl':('Ik geef toestemming dat JaMi Protect deze review openbaar publiceert (mijn e-mailadres wordt niet gepubliceerd).','Opende je mailapp niet? Kopieer de review hieronder en verstuur hem handmatig.','Reviewtekst kopiëren','Kies eerst een beoordeling.','Je mailapp hoort te openen. Gebeurt dat niet, gebruik dan de kopieeroptie hieronder.','Review is naar je klembord gekopieerd.'),'de':('Ich stimme zu, dass JaMi Protect diese Review öffentlich veröffentlicht (meine E-Mail-Adresse wird nicht veröffentlicht).','E-Mail-App nicht geöffnet? Kopiere die Review unten und sende sie manuell.','Review-Text kopieren','Bitte zuerst eine Bewertung wählen.','Deine E-Mail-App sollte sich öffnen. Falls nicht, nutze unten die Kopieroption.','Review wurde in die Zwischenablage kopiert.'),'fr':('J’accepte que JaMi Protect publie cet avis publiquement (mon adresse e-mail ne sera pas publiée).','L’application e-mail ne s’est pas ouverte ? Copiez l’avis ci-dessous et envoyez-le manuellement.','Copier le texte de l’avis','Choisissez d’abord une note.','Votre application e-mail devrait s’ouvrir. Sinon, utilisez l’option de copie ci-dessous.','Avis copié dans le presse-papiers.')}
NF={'en':('Page not found','The page you requested does not exist or has moved.','Back to home →'),'nl':('Pagina niet gevonden','De pagina die je zoekt bestaat niet of is verplaatst.','Terug naar home →'),'de':('Seite nicht gefunden','Die angeforderte Seite existiert nicht oder wurde verschoben.','Zur Startseite →'),'fr':('Page introuvable','La page demandée n’existe pas ou a été déplacée.','Retour à l’accueil →')}
def locale(p):
 q=p.relative_to(ROOT).parts;return q[0] if q and q[0] in ('nl','de','fr') else 'en'
def patch(s,p,l):
 m=s.head.find('meta',attrs={'name':'jami-build'});m['content']='V6.9.0' if m else None
 for tag in s.find_all(['link','script','img']):
  a='href' if tag.name=='link' else 'src';u=tag.get(a)
  if not u:continue
  u=u.replace('jami-v6-8.css','jami-v6-9.css').replace('site-v6-8.js','site-v6-9.js').replace('covers-v6-8.js','covers-v6-9.js').replace('config-v6-8.js','config-v6-9.js').replace('review-form-v6-8.js','review-form-v6-9.js');u=re.sub(r'\?v=6\.8(?:\.\d+)?', '?v=6.9.0',u);tag[a]=u
 if not s.head.find('link',rel='manifest'):s.head.append(s.new_tag('link',rel='manifest',href='/jami-protect/site.webmanifest'))
 if not s.head.find('meta',attrs={'name':'theme-color'}):s.head.append(s.new_tag('meta',attrs={'name':'theme-color','content':'#070b10'}))
 if not s.head.find('link',rel='apple-touch-icon'):s.head.append(s.new_tag('link',rel='apple-touch-icon',href='/jami-protect/assets/branding/jami-mark.png'))
 nav=s.select_one('.nav-links');tog=s.select_one('.nav-toggle');desk=s.select_one('.language-switch')
 if nav:
  nav['id']='site-nav';old=nav.select_one('.mobile-language-switch');old and old.decompose()
  if desk:
   mob=s.new_tag('div',attrs={'class':'mobile-language-switch','aria-label':NAV[l][2]});[mob.append(BeautifulSoup(str(a),'html.parser').a) for a in desk.find_all('a',recursive=False)];nav.append(mob);desk['aria-label']=NAV[l][2]
 if tog:tog['aria-controls']='site-nav';tog['aria-expanded']='false';tog['aria-label']=NAV[l][0];tog['data-open-label']=NAV[l][0];tog['data-close-label']=NAV[l][1]
 for a in s.find_all('a',href=True):
  if a['href'].startswith('http'):a['rel']='noopener noreferrer'
 if l!='en':
  for node in list(s.find_all(string=True)):
   if node.parent and node.parent.name in ('script','style'):continue
   tx=str(node)
   for old,new in REPL[l].items():tx=tx.replace(old,new)
   if tx!=str(node):node.replace_with(tx)
 # exact titles
 for node in list(s.find_all(string=True)):
  if node.parent and node.parent.name in ('script','style'):continue
  tx=str(node).replace('Grand Theft Auto IV: The Complete Edition: The Complete Edition','Grand Theft Auto IV: The Complete Edition').replace('Grand Theft Auto IV','Grand Theft Auto IV: The Complete Edition').replace('Grand Theft Auto IV: The Complete Edition: The Complete Edition','Grand Theft Auto IV: The Complete Edition').replace('Minecraft Java','Minecraft: Java Edition')
  if tx!=str(node):node.replace_with(tx)
 # home schema
 rel=str(p.relative_to(ROOT))
 if rel in ('index.html','nl/index.html','de/index.html','fr/index.html'):
  old=s.head.find('script',attrs={'type':'application/ld+json'});old and old.decompose();root='/' if l=='en' else f'/{l}/';obj={'@context':'https://schema.org','@graph':[{'@type':'WebSite','name':'JaMi Protect','url':BASE+root,'inLanguage':l},{'@type':'SoftwareApplication','name':'JaMi Protect','applicationCategory':'UtilitiesApplication','operatingSystem':'Windows 10, Windows 11','url':BASE+root,'softwareVersion':'Preview'}]};x=s.new_tag('script',type='application/ld+json');x.string=json.dumps(obj,separators=(',',':'));s.head.append(x)
 # privacy
 if p.name=='privacy.html':
  h,lead,secs=PRIV[l];cards=''.join(f'<article class="policy-card"><h2>{a}</h2><p>{b}</p></article>' for a,b in secs);s.find('main').replace_with(BeautifulSoup(f'<main><section class="section"><div class="container policy-wrap"><div class="kicker">Privacy</div><h1>{h}</h1><p class="hero-copy">{lead}</p><div class="policy-grid">{cards}</div></div></section></main>','html.parser').main)
 # review form
 form=s.select_one('#review-form')
 if form:
  r=REV[l];form['data-rating-error']=r[3];form['data-mail-status']=r[4];form['data-copy-success']=r[5]
  for fld in form.select('.review-field'):
   ctl=fld.find(['input','textarea','select']);lab=fld.find('label')
   if ctl and lab and ctl.get('name') and ctl.get('type')!='hidden':cid='review-'+ctl['name'].replace('_','-');ctl['id']=cid;lab['for']=cid
  pick=form.select_one('.star-picker');
  if pick:pick['role']='group';pick['aria-label']='Rating'
  if not form.select_one('[name="publish_consent"]'):
   consent=BeautifulSoup(f'<label class="consent-box"><input type="checkbox" name="publish_consent" value="yes"><span>{r[0]}</span></label>','html.parser').label;form.select_one('.actions').insert_before(consent)
  if not form.select_one('[data-review-fallback]'):
   fb=BeautifulSoup(f'<div class="review-fallback" data-review-fallback hidden><strong>{r[1]}</strong><textarea data-review-copy-text readonly aria-label="Review text"></textarea><button class="btn btn-secondary" type="button" data-copy-review>{r[2]}</button></div>','html.parser').div;form.select_one('[data-submit-status]').insert_after(fb)
 return s
for p in list(ROOT.rglob('*.html')):
 l=locale(p);s=BeautifulSoup(p.read_text(),'html.parser');patch(s,p,l);p.write_text(str(s))
# 404 locales based on local homepage header/footer
for l in locs:
 src=ROOT/'404.html' if l=='en' else ROOT/l/'index.html';s=BeautifulSoup(src.read_text(),'html.parser');title,msg,btn=NF[l];s.title.string=title+' | JaMi Protect';rob=s.head.find('meta',attrs={'name':'robots'});rob['content']='noindex,follow';home='/jami-protect/' if l=='en' else f'/jami-protect/{l}/';games=home+'games/';s.find('main').replace_with(BeautifulSoup(f'<main><section class="section"><div class="container policy-wrap"><div class="kicker">404</div><h1>{title}</h1><p class="hero-copy">{msg}</p><div class="actions"><a class="btn btn-primary" href="{home}">{btn}</a><a class="btn btn-secondary" href="{games}">Games</a></div></div></section></main>','html.parser').main);target=ROOT/'404.html' if l=='en' else ROOT/l/'404.html';patch(s,target,l);target.write_text(str(s))
print('global patched')
